adminUser:
  password: vault:swallowfire/adminUser:password
  username: admin
dashboardUrl: https://dashboard.play-jxaas.live
enableDocker: false
pipelineUser:
  email: arcalos-admin@googlegroups.com
  token: vault:swallowfire/pipelineUser:token
  username: cloudbees-ci-cd-play[bot]
prow:
  hmacToken: vault:swallowfire/prow:hmacToken
segmentWriteKey: vault:swallowfire:segmentWriteKey
